nameOverride: frontend
replicaCount: 1

image:
  repository: abstraxlk/task-management-frontend
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: taskmanager.local
  path: /

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
