nameOverride: frontend
replicaCount: 1

image:
  repository: abstraxlk/task-management-frontend
  tag: 3
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
