apiVersion: v1
kind: Secret
metadata:
  name: task-management-secrets
  namespace: task-management
type: Opaque
stringData:
  auth-mongodb-uri: mongodb+srv://USER:PASSWORD@cluster.example.mongodb.net/task_management_auth
  task-mongodb-uri: mongodb+srv://USER:PASSWORD@cluster.example.mongodb.net/task_management_tasks
  jwt-secret: replace-with-a-long-random-secret
